export interface TechDefinition {
  name: string
  skill?: string
  logo?: string
  color?: string
}

export const technologyGroups: Record<string, TechDefinition[]> = {
  Languages: [
    { name: 'TypeScript', skill: 'ts', logo: 'typescript', color: '3178C6' },
    { name: 'JavaScript', skill: 'js', logo: 'javascript', color: 'F7DF1E' },
    { name: 'Python', skill: 'py', logo: 'python', color: '3776AB' },
    { name: 'Rust', skill: 'rust', logo: 'rust', color: '000000' },
    { name: 'Go', skill: 'go', logo: 'go', color: '00ADD8' },
    { name: 'Java', skill: 'java', logo: 'openjdk', color: 'ED8B00' },
    { name: 'Kotlin', skill: 'kotlin', logo: 'kotlin', color: '7F52FF' },
    { name: 'C#', skill: 'cs', logo: 'csharp', color: '512BD4' },
    { name: 'C', skill: 'c', logo: 'c', color: 'A8B9CC' },
    { name: 'C++', skill: 'cpp', logo: 'cplusplus', color: '00599C' },
    { name: 'Swift', skill: 'swift', logo: 'swift', color: 'F05138' },
    { name: 'Dart', skill: 'dart', logo: 'dart', color: '0175C2' },
    { name: 'PHP', skill: 'php', logo: 'php', color: '777BB4' },
    { name: 'Ruby', skill: 'ruby', logo: 'ruby', color: 'CC342D' },
    { name: 'Scala', skill: 'scala', logo: 'scala', color: 'DC322F' },
    { name: 'R', skill: 'r', logo: 'r', color: '276DC3' },
    { name: 'Lua', skill: 'lua', logo: 'lua', color: '2C2D72' },
    { name: 'Perl', skill: 'perl', logo: 'perl', color: '39457E' },
    { name: 'Elixir', skill: 'elixir', logo: 'elixir', color: '4B275F' },
    { name: 'Erlang', skill: 'erlang', logo: 'erlang', color: 'A90533' },
    { name: 'Haskell', skill: 'haskell', logo: 'haskell', color: '5D4F85' },
    { name: 'Clojure', skill: 'clojure', logo: 'clojure', color: '5881D8' },
    { name: 'F#', skill: 'fsharp', logo: 'fsharp', color: '378BBA' },
    { name: 'Zig', skill: 'zig', logo: 'zig', color: 'F7A41D' },
    { name: 'Nim', logo: 'nim', color: 'FFE953' },
    { name: 'Solidity', skill: 'solidity', logo: 'solidity', color: '363636' },
    { name: 'Objective-C', logo: 'apple', color: '000000' },
    { name: 'Visual Basic', logo: 'dotnet', color: '512BD4' },
    { name: 'Bash', skill: 'bash', logo: 'gnubash', color: '4EAA25' },
    { name: 'PowerShell', skill: 'powershell', logo: 'powershell', color: '5391FE' }
  ],
  Frontend: [
    { name: 'HTML5', skill: 'html', logo: 'html5', color: 'E34F26' },
    { name: 'CSS3', skill: 'css', logo: 'css', color: '663399' },
    { name: 'React', skill: 'react', logo: 'react', color: '61DAFB' },
    { name: 'Next.js', skill: 'nextjs', logo: 'nextdotjs', color: '000000' },
    { name: 'Vue', skill: 'vue', logo: 'vuedotjs', color: '4FC08D' },
    { name: 'Nuxt', skill: 'nuxtjs', logo: 'nuxt', color: '00DC82' },
    { name: 'Svelte', skill: 'svelte', logo: 'svelte', color: 'FF3E00' },
    { name: 'SvelteKit', logo: 'svelte', color: 'FF3E00' },
    { name: 'Angular', skill: 'angular', logo: 'angular', color: '0F0F11' },
    { name: 'SolidJS', skill: 'solidjs', logo: 'solid', color: '2C4F7C' },
    { name: 'Qwik', logo: 'qwik', color: 'AC7EF4' },
    { name: 'Astro', skill: 'astro', logo: 'astro', color: 'BC52EE' },
    { name: 'Remix', skill: 'remix', logo: 'remix', color: '000000' },
    { name: 'Gatsby', skill: 'gatsby', logo: 'gatsby', color: '663399' },
    { name: 'Preact', logo: 'preact', color: '673AB8' },
    { name: 'Alpine.js', logo: 'alpinedotjs', color: '8BC0D0' },
    { name: 'HTMX', skill: 'htmx', logo: 'htmx', color: '3366CC' },
    { name: 'jQuery', logo: 'jquery', color: '0769AD' },
    { name: 'Redux', skill: 'redux', logo: 'redux', color: '764ABC' },
    { name: 'Zustand', logo: 'react', color: '443E38' },
    { name: 'MobX', logo: 'mobx', color: 'FF9955' },
    { name: 'Pinia', skill: 'pinia', logo: 'pinia', color: 'FFD859' },
    { name: 'Tailwind CSS', skill: 'tailwind', logo: 'tailwindcss', color: '06B6D4' },
    { name: 'Bootstrap', skill: 'bootstrap', logo: 'bootstrap', color: '7952B3' },
    { name: 'Sass', skill: 'sass', logo: 'sass', color: 'CC6699' },
    { name: 'Less', skill: 'less', logo: 'less', color: '1D365D' },
    { name: 'Styled Components', skill: 'styledcomponents', logo: 'styledcomponents', color: 'DB7093' },
    { name: 'Material UI', skill: 'materialui', logo: 'mui', color: '007FFF' },
    { name: 'Chakra UI', logo: 'chakraui', color: '319795' },
    { name: 'Ant Design', logo: 'antdesign', color: '0170FE' },
    { name: 'shadcn/ui', logo: 'shadcnui', color: '000000' },
    { name: 'Storybook', logo: 'storybook', color: 'FF4785' },
    { name: 'Three.js', skill: 'threejs', logo: 'threedotjs', color: '000000' }
  ],
  Backend: [
    { name: 'Node.js', skill: 'nodejs', logo: 'nodedotjs', color: '5FA04E' },
    { name: 'Express', skill: 'express', logo: 'express', color: '000000' },
    { name: 'NestJS', skill: 'nestjs', logo: 'nestjs', color: 'E0234E' },
    { name: 'Fastify', skill: 'fastify', logo: 'fastify', color: '000000' },
    { name: 'Hono', logo: 'hono', color: 'E36002' },
    { name: 'Deno', skill: 'deno', logo: 'deno', color: '70FFAF' },
    { name: 'Bun', skill: 'bun', logo: 'bun', color: '000000' },
    { name: 'FastAPI', skill: 'fastapi', logo: 'fastapi', color: '009688' },
    { name: 'Django', skill: 'django', logo: 'django', color: '092E20' },
    { name: 'Flask', skill: 'flask', logo: 'flask', color: '000000' },
    { name: 'Spring', skill: 'spring', logo: 'spring', color: '6DB33F' },
    { name: 'ASP.NET Core', skill: 'dotnet', logo: 'dotnet', color: '512BD4' },
    { name: 'Laravel', skill: 'laravel', logo: 'laravel', color: 'FF2D20' },
    { name: 'Symfony', logo: 'symfony', color: '000000' },
    { name: 'Ruby on Rails', skill: 'rails', logo: 'rubyonrails', color: 'D30001' },
    { name: 'Phoenix', logo: 'phoenixframework', color: 'FD4F00' },
    { name: 'Actix', skill: 'actix', logo: 'rust', color: '000000' },
    { name: 'Gin', logo: 'go', color: '00ADD8' },
    { name: 'Fiber', logo: 'go', color: '00ADD8' },
    { name: 'GraphQL', skill: 'graphql', logo: 'graphql', color: 'E10098' },
    { name: 'Apollo GraphQL', logo: 'apollographql', color: '311C87' },
    { name: 'tRPC', logo: 'trpc', color: '2596BE' },
    { name: 'Prisma', skill: 'prisma', logo: 'prisma', color: '2D3748' },
    { name: 'Drizzle ORM', logo: 'drizzle', color: 'C5F74F' },
    { name: 'Hibernate', skill: 'hibernate', logo: 'hibernate', color: '59666C' }
  ],
  Desktop: [
    { name: 'Electron', skill: 'electron', logo: 'electron', color: '47848F' },
    { name: 'Tauri', skill: 'tauri', logo: 'tauri', color: '24C8DB' },
    { name: 'Qt', skill: 'qt', logo: 'qt', color: '41CD52' },
    { name: 'GTK', skill: 'gtk', logo: 'gtk', color: '7FE719' },
    { name: 'WPF', logo: 'dotnet', color: '512BD4' },
    { name: 'WinUI', logo: 'windows11', color: '0078D4' },
    { name: 'Avalonia', logo: 'dotnet', color: '8B44AC' },
    { name: 'JavaFX', logo: 'openjdk', color: 'ED8B00' }
  ],
  Mobile: [
    { name: 'Android', skill: 'androidstudio', logo: 'android', color: '3DDC84' },
    { name: 'Jetpack Compose', logo: 'jetpackcompose', color: '4285F4' },
    { name: 'iOS', logo: 'ios', color: '000000' },
    { name: 'SwiftUI', logo: 'swift', color: 'F05138' },
    { name: 'React Native', skill: 'react', logo: 'react', color: '61DAFB' },
    { name: 'Expo', logo: 'expo', color: '000020' },
    { name: 'Flutter', skill: 'flutter', logo: 'flutter', color: '02569B' },
    { name: 'Ionic', logo: 'ionic', color: '3880FF' },
    { name: 'Xamarin', logo: 'xamarin', color: '3498DB' },
    { name: 'MAUI', logo: 'dotnet', color: '512BD4' }
  ],
  'Game & Graphics': [
    { name: 'Unity', skill: 'unity', logo: 'unity', color: '000000' },
    { name: 'Unreal Engine', skill: 'unreal', logo: 'unrealengine', color: '0E1128' },
    { name: 'Godot', skill: 'godot', logo: 'godotengine', color: '478CBF' },
    { name: 'Blender', skill: 'blender', logo: 'blender', color: 'E87D0D' },
    { name: 'OpenGL', logo: 'opengl', color: '5586A4' },
    { name: 'Vulkan', logo: 'vulkan', color: 'AC162C' },
    { name: 'DirectX', logo: 'windows', color: '0078D4' },
    { name: 'SDL', skill: 'sdl', logo: 'cplusplus', color: '17314D' },
    { name: 'Raylib', logo: 'c', color: '000000' }
  ],
  Databases: [
    { name: 'PostgreSQL', skill: 'postgres', logo: 'postgresql', color: '4169E1' },
    { name: 'MySQL', skill: 'mysql', logo: 'mysql', color: '4479A1' },
    { name: 'MariaDB', skill: 'mariadb', logo: 'mariadb', color: '003545' },
    { name: 'SQLite', skill: 'sqlite', logo: 'sqlite', color: '003B57' },
    { name: 'MongoDB', skill: 'mongodb', logo: 'mongodb', color: '47A248' },
    { name: 'Redis', skill: 'redis', logo: 'redis', color: 'FF4438' },
    { name: 'Valkey', logo: 'redis', color: 'FF4438' },
    { name: 'Supabase', skill: 'supabase', logo: 'supabase', color: '3FCF8E' },
    { name: 'Firebase', skill: 'firebase', logo: 'firebase', color: 'DD2C00' },
    { name: 'DynamoDB', skill: 'dynamodb', logo: 'amazondynamodb', color: '4053D6' },
    { name: 'Cassandra', skill: 'cassandra', logo: 'apachecassandra', color: '1287B1' },
    { name: 'CockroachDB', logo: 'cockroachlabs', color: '6933FF' },
    { name: 'Neo4j', skill: 'neo4j', logo: 'neo4j', color: '4581C3' },
    { name: 'InfluxDB', logo: 'influxdb', color: '22ADF6' },
    { name: 'ClickHouse', logo: 'clickhouse', color: 'FFCC01' },
    { name: 'Elasticsearch', skill: 'elasticsearch', logo: 'elasticsearch', color: '005571' },
    { name: 'PlanetScale', logo: 'planetscale', color: '000000' },
    { name: 'Oracle', skill: 'oracle', logo: 'oracle', color: 'F80000' },
    { name: 'Microsoft SQL Server', logo: 'microsoftsqlserver', color: 'CC2927' }
  ],
  'Cloud & Hosting': [
    { name: 'AWS', skill: 'aws', logo: 'amazonwebservices', color: '232F3E' },
    { name: 'Google Cloud', skill: 'gcp', logo: 'googlecloud', color: '4285F4' },
    { name: 'Azure', skill: 'azure', logo: 'microsoftazure', color: '0078D4' },
    { name: 'Cloudflare', skill: 'cloudflare', logo: 'cloudflare', color: 'F38020' },
    { name: 'Vercel', skill: 'vercel', logo: 'vercel', color: '000000' },
    { name: 'Netlify', skill: 'netlify', logo: 'netlify', color: '00C7B7' },
    { name: 'Render', logo: 'render', color: '000000' },
    { name: 'Railway', logo: 'railway', color: '0B0D0E' },
    { name: 'Fly.io', logo: 'flydotio', color: '8B5CF6' },
    { name: 'Heroku', skill: 'heroku', logo: 'heroku', color: '430098' },
    { name: 'DigitalOcean', logo: 'digitalocean', color: '0080FF' },
    { name: 'Linode', logo: 'linode', color: '00A95C' },
    { name: 'Hetzner', logo: 'hetzner', color: 'D50C2D' }
  ],
  DevOps: [
    { name: 'Git', skill: 'git', logo: 'git', color: 'F05032' },
    { name: 'GitHub', skill: 'github', logo: 'github', color: '181717' },
    { name: 'GitLab', skill: 'gitlab', logo: 'gitlab', color: 'FC6D26' },
    { name: 'Docker', skill: 'docker', logo: 'docker', color: '2496ED' },
    { name: 'Kubernetes', skill: 'kubernetes', logo: 'kubernetes', color: '326CE5' },
    { name: 'Helm', logo: 'helm', color: '0F1689' },
    { name: 'Terraform', skill: 'terraform', logo: 'terraform', color: '844FBA' },
    { name: 'Ansible', skill: 'ansible', logo: 'ansible', color: 'EE0000' },
    { name: 'Jenkins', skill: 'jenkins', logo: 'jenkins', color: 'D24939' },
    { name: 'GitHub Actions', skill: 'githubactions', logo: 'githubactions', color: '2088FF' },
    { name: 'CircleCI', logo: 'circleci', color: '343434' },
    { name: 'Travis CI', logo: 'travisci', color: '3EAAAF' },
    { name: 'Argo CD', logo: 'argo', color: 'EF7B4D' },
    { name: 'Prometheus', skill: 'prometheus', logo: 'prometheus', color: 'E6522C' },
    { name: 'Grafana', skill: 'grafana', logo: 'grafana', color: 'F46800' },
    { name: 'Nginx', skill: 'nginx', logo: 'nginx', color: '009639' },
    { name: 'Apache', logo: 'apache', color: 'D22128' },
    { name: 'Caddy', logo: 'caddy', color: '1F88C0' }
  ],
  'Build & Package': [
    { name: 'Vite', skill: 'vite', logo: 'vite', color: '646CFF' },
    { name: 'Webpack', skill: 'webpack', logo: 'webpack', color: '8DD6F9' },
    { name: 'Rollup', skill: 'rollupjs', logo: 'rollupdotjs', color: 'EC4A3F' },
    { name: 'esbuild', logo: 'esbuild', color: 'FFCF00' },
    { name: 'Turborepo', logo: 'turborepo', color: 'EF4444' },
    { name: 'Nx', logo: 'nx', color: '143055' },
    { name: 'npm', skill: 'npm', logo: 'npm', color: 'CB3837' },
    { name: 'pnpm', skill: 'pnpm', logo: 'pnpm', color: 'F69220' },
    { name: 'Yarn', skill: 'yarn', logo: 'yarn', color: '2C8EBB' },
    { name: 'Composer', logo: 'composer', color: '885630' },
    { name: 'Gradle', skill: 'gradle', logo: 'gradle', color: '02303A' },
    { name: 'Maven', skill: 'maven', logo: 'apachemaven', color: 'C71A36' },
    { name: 'CMake', skill: 'cmake', logo: 'cmake', color: '064F8C' },
    { name: 'Meson', logo: 'meson', color: '007800' }
  ],
  Testing: [
    { name: 'Vitest', skill: 'vitest', logo: 'vitest', color: '6E9F18' },
    { name: 'Jest', skill: 'jest', logo: 'jest', color: 'C21325' },
    { name: 'Playwright', logo: 'playwright', color: '2EAD33' },
    { name: 'Cypress', skill: 'cypress', logo: 'cypress', color: '69D3A7' },
    { name: 'Selenium', skill: 'selenium', logo: 'selenium', color: '43B02A' },
    { name: 'Pytest', logo: 'pytest', color: '0A9EDC' },
    { name: 'JUnit', logo: 'junit5', color: '25A162' },
    { name: 'Postman', skill: 'postman', logo: 'postman', color: 'FF6C37' },
    { name: 'Insomnia', logo: 'insomnia', color: '4000BF' }
  ],
  'Data & AI': [
    { name: 'NumPy', logo: 'numpy', color: '013243' },
    { name: 'Pandas', logo: 'pandas', color: '150458' },
    { name: 'Jupyter', logo: 'jupyter', color: 'F37626' },
    { name: 'TensorFlow', skill: 'tensorflow', logo: 'tensorflow', color: 'FF6F00' },
    { name: 'PyTorch', skill: 'pytorch', logo: 'pytorch', color: 'EE4C2C' },
    { name: 'scikit-learn', skill: 'sklearn', logo: 'scikitlearn', color: 'F7931E' },
    { name: 'OpenCV', skill: 'opencv', logo: 'opencv', color: '5C3EE8' },
    { name: 'Hugging Face', logo: 'huggingface', color: 'FFD21E' },
    { name: 'OpenAI', logo: 'openai', color: '412991' },
    { name: 'LangChain', logo: 'langchain', color: '1C3C3C' },
    { name: 'Apache Spark', logo: 'apachespark', color: 'E25A1C' }
  ],
  Editors: [
    { name: 'VS Code', skill: 'vscode', logo: 'visualstudiocode', color: '007ACC' },
    { name: 'Visual Studio', skill: 'visualstudio', logo: 'visualstudio', color: '5C2D91' },
    { name: 'IntelliJ IDEA', skill: 'idea', logo: 'intellijidea', color: '000000' },
    { name: 'Android Studio', skill: 'androidstudio', logo: 'androidstudio', color: '3DDC84' },
    { name: 'Xcode', logo: 'xcode', color: '147EFB' },
    { name: 'Neovim', skill: 'neovim', logo: 'neovim', color: '57A143' },
    { name: 'Vim', skill: 'vim', logo: 'vim', color: '019733' },
    { name: 'Sublime Text', logo: 'sublimetext', color: 'FF9800' },
    { name: 'JetBrains Rider', skill: 'rider', logo: 'rider', color: '000000' },
    { name: 'PyCharm', skill: 'pycharm', logo: 'pycharm', color: '000000' }
  ],
  Design: [
    { name: 'Figma', skill: 'figma', logo: 'figma', color: 'F24E1E' },
    { name: 'Adobe Photoshop', skill: 'photoshop', logo: 'adobephotoshop', color: '31A8FF' },
    { name: 'Adobe Illustrator', skill: 'illustrator', logo: 'adobeillustrator', color: 'FF9A00' },
    { name: 'After Effects', skill: 'aftereffects', logo: 'adobeaftereffects', color: '9999FF' },
    { name: 'Premiere Pro', skill: 'premiere', logo: 'adobepremierepro', color: '9999FF' },
    { name: 'Framer', logo: 'framer', color: '0055FF' },
    { name: 'Sketch', logo: 'sketch', color: 'F7B500' }
  ],
  Platforms: [
    { name: 'Linux', skill: 'linux', logo: 'linux', color: 'FCC624' },
    { name: 'Ubuntu', skill: 'ubuntu', logo: 'ubuntu', color: 'E95420' },
    { name: 'Debian', skill: 'debian', logo: 'debian', color: 'A81D33' },
    { name: 'Arch Linux', skill: 'arch', logo: 'archlinux', color: '1793D1' },
    { name: 'Windows', logo: 'windows11', color: '0078D4' },
    { name: 'macOS', logo: 'apple', color: '000000' },
    { name: 'Raspberry Pi', skill: 'raspberrypi', logo: 'raspberrypi', color: 'A22846' }
  ],
  'CMS & Content': [
    { name: 'WordPress', skill: 'wordpress', logo: 'wordpress', color: '21759B' },
    { name: 'Strapi', logo: 'strapi', color: '4945FF' },
    { name: 'Sanity', logo: 'sanity', color: 'F03E2F' },
    { name: 'Contentful', logo: 'contentful', color: '2478CC' },
    { name: 'Directus', logo: 'directus', color: '263238' },
    { name: 'Payload CMS', logo: 'payloadcms', color: '000000' }
  ],
  Protocols: [
    { name: 'REST', logo: 'openapiinitiative', color: '6BA539' },
    { name: 'OpenAPI', logo: 'openapiinitiative', color: '6BA539' },
    { name: 'WebSocket', logo: 'socketdotio', color: '010101' },
    { name: 'gRPC', logo: 'google', color: '244C5A' },
    { name: 'MQTT', logo: 'mqtt', color: '660066' },
    { name: 'RabbitMQ', skill: 'rabbitmq', logo: 'rabbitmq', color: 'FF6600' },
    { name: 'Apache Kafka', skill: 'kafka', logo: 'apachekafka', color: '231F20' }
  ]
}

export const technologyIndex = Object.values(technologyGroups).flat().reduce<Record<string, TechDefinition>>((index, tech) => {
  index[tech.name] = tech
  return index
}, {})

export const techPresets: Record<string, string[]> = {
  'Frontend': ['TypeScript', 'React', 'Next.js', 'Tailwind CSS', 'Vite'],
  'Fullstack JS': ['TypeScript', 'React', 'Next.js', 'Node.js', 'PostgreSQL', 'Prisma', 'Docker'],
  'Python API': ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker'],
  'Android': ['Kotlin', 'Android', 'Jetpack Compose', 'Firebase', 'Gradle'],
  'iOS': ['Swift', 'iOS', 'SwiftUI', 'Xcode'],
  '.NET': ['C#', 'ASP.NET Core', 'Microsoft SQL Server', 'Docker', 'Azure'],
  'Game Dev': ['C++', 'C#', 'Unity', 'Unreal Engine', 'Blender'],
  'DevOps': ['Linux', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions', 'Nginx', 'Prometheus', 'Grafana'],
  'Data / AI': ['Python', 'NumPy', 'Pandas', 'Jupyter', 'PyTorch', 'Hugging Face']
}
